const meatTypes = {
  "Huesos Carnosos": [
    {
      name: "Alitas de pollo",
      img: require("../../assets/food/alitas_pollo.webp"),
    },
    {
      name: "Carcasas de pollo",
      img: require("../../assets/food/carcasas_pollo.webp"),
    },
    {
      name: "Cuellos  de pollo",
      img: require("../../assets/food/cuello_pollo.webp"),
    },
    {
      name: "Puntas de alitas de pollo",
      img: require("../../assets/food/puntas_alitas_pollo.webp"),
    },
    {
      name: "Trasero de pollo",
      img: require("../../assets/food/trasero_pollo.webp"),
    },
    {
      name: "Alas de pavo",
      img: require("../../assets/food/alas_pavo.webp"),
    },
    {
      name: "Carcasas de pavo",
      img: require("../../assets/food/carcasa-de-pavo.webp"),
    },
    {
      name: "Cuellos de pavo",
      img: require("../../assets/food/cuello_pavo.webp"),
    },
    {
      name: "Carcasas de pato",
      img: require("../../assets/food/carcasa_pato.webp"),
    },
    {
      name: "Cuellos de pato",
      img: require("../../assets/food/cuello_pato.webp"),
    },
    {
      name: "Costillas de cerdo",
      img: require("../../assets/food/costillas_cerdo.webp"),
    },
    {
      name: "Costillas de conejo",
      img: require("../../assets/food/costillas_conejo.webp"),
    },
    {
      name: "Costillas de ternera",
      img: require("../../assets/food/costillas_ternera.webp"),
    },
    {
      name: "Cuello de ternera",
      img: require("../../assets/food/cuello-ternera.webp"),
    },
    {
      name: "Pecho de ternera",
      img: require("../../assets/food/pecho-de-ternera.webp"),
    },
    {
      name: "Cuello de cordero",
      img: require("../../assets/food/cuello-cordero.webp"),
    },
    {
      name: "Falda de cordero",
      img: require("../../assets/food/falda_cordero.webp"),
    },
  ],
  Carne: [
    { name: "Pollo", img: require("../../assets/food/pollo.webp") },
    { name: "Pavo", img: require("../../assets/food/pavo.webp") },
    { name: "Pato", img: require("../../assets/food/pato.webp") },
    { name: "Gallina", img: require("../../assets/food/gallina.webp") },
    { name: "Ternera", img: require("../../assets/food/ternera.webp") },
    { name: "Cordero", img: require("../../assets/food/cordero.webp") },
    { name: "Conejo", img: require("../../assets/food/conejo.webp") },
    { name: "Cerdo", img: require("../../assets/food/cerdo.webp") },
    { name: "Cabra", img: require("../../assets/food/cabra.webp") },
    { name: "Ciervo", img: require("../../assets/food/ciervo.webp") },
    { name: "Caballo", img: require("../../assets/food/caballo.webp") },
    { name: "Toro", img: require("../../assets/food/toro.webp") },
    { name: "Avestruz", img: require("../../assets/food/avestruz.webp") },
    { name: "Canguro", img: require("../../assets/food/canguro.webp") },
    {
      name: "Corazon de pollo",
      img: require("../../assets/food/corazon_pollo.webp"),
    },
    {
      name: "Corazon de pavo",
      img: require("../../assets/food/corazon_pato.webp"),
    },
    {
      name: "Corazon de pato",
      img: require("../../assets/food/corazon_pato.webp"),
    },
    {
      name: "Corazon de ternera",
      img: require("../../assets/food/corazon_ternera.webp"),
    },
    {
      name: "Corazon de cerdo",
      img: require("../../assets/food/corazon-de-cerdo.webp"),
    },
    {
      name: "Corazon de cordero",
      img: require("../../assets/food/corazon-cordero.webp"),
    },
    {
      name: "Corazon de caballo",
      img: require("../../assets/food/corazon-vaca.webp"),
    },
    {
      name: "Lengua de ternera",
      img: require("../../assets/food/lengua_ternera.webp"),
    },
    {
      name: "Lengua de cerdo",
      img: require("../../assets/food/lengua_cerdo.webp"),
    },
    {
      name: "Lengua de cordero",
      img: require("../../assets/food/lengua_cordero.webp"),
    },
    {
      name: "Mollejas de pollo",
      img: require("../../assets/food/mollejas_pollo.webp"),
    },
    {
      name: "Mollejas de pavo",
      img: require("../../assets/food/mollejas_pavo.webp"),
    },
    {
      name: "Mollejas de pato",
      img: require("../../assets/food/mollejas_pato.webp"),
    },
    {
      name: "Tripa verde de ternera",
      img: require("../../assets/food/tripa_verde.webp"),
    },
  ],
  Pescado: [
    { name: "Abadejo", img: require("../../assets/food/pescado/abadejo.webp") },
    { name: "Anchoa", img: require("../../assets/food/pescado/anchoa.webp") },
    { name: "Anguila", img: require("../../assets/food/pescado/anguila.webp") },
    { name: "Arenque", img: require("../../assets/food/pescado/arenque.webp") },
    { name: "Atun", img: require("../../assets/food/pescado/atun.webp") },
    { name: "Bacaladilla" },
    { name: "Bacalao" },
    { name: "Besugo" },
    { name: "Boqueron" },
    { name: "Breca" },
    { name: "Caballa" },
    { name: "Cabracho" },
    { name: "Caz`on" },
    { name: "Congrio" },
    { name: "Dorada" },
    { name: "Faneca" },
    { name: "Gallo" },
    { name: "Flet`an" },
    { name: "Jurel" },
    { name: "Lamprea" },
    { name: "Lenguado" },
    { name: "Lubina" },
    { name: "Merluza" },
    { name: "Mero" },
    { name: "Mujol" },
    { name: "Palometa" },
    { name: "Pescadilla" },
    { name: "Platija" },
    { name: "Rape" },
    { name: "Raya" },
    { name: "Rodaballo" },
    { name: "Rosada" },
    { name: "Salmonete" },
    { name: "Salmon" },
    { name: "Sama" },
    { name: "Sardina" },
    { name: "Trucha" },
  ],
  Hígado: [
    { name: "Hígado de cerdo" },
    { name: "Hígado de ternera" },
    { name: "Higado de cabra" },
    { name: "Higado de conejo" },
    { name: "Higado de cordero" },
    { name: "Higado de pollo" },
    { name: "Higado de caballo" },
  ],
  "Mas Visceras": [
    { name: "Asadura de cerdo" },
    { name: "Asadura de conejo" },
    { name: "Asadura de ternera" },
    { name: "Bazo de caballo" },
    { name: "Bazo de cerdo" },
    { name: "Bazo de cordero" },
    { name: "Bazo de ternera" },
    { name: "Criadilla de caballo" },
    { name: "Criadilla de cerdo" },
    { name: "Criadilla de cordero" },
    { name: "Criadilla de toro" },
    { name: "Molleja de caballo" },
    { name: "Molleja de cordero" },
    { name: "Molleja de ternera" },
    { name: "Pulmon de caballo" },
    { name: "Pulmon de cerdo" },
    { name: "Pulmon de cordero" },
    { name: "Pulmon de ternera" },
    { name: "Pancreas de cerdo" },
    { name: "Pancreas de ternera" },
    { name: "Rinon de caballo" },
    { name: "Rinon de cerdo" },
    { name: "Rinon de cordero" },
    { name: "Rinon de ternera" },
    { name: "Sesos de caballo" },
    { name: "Sesos de cerdo" },
    { name: "Sesos de cordero" },
    { name: "Sesos de ternera" },
  ],
  "Frutas y verduras": [{ name: "Manzana" }, { name: "Zanahoria" }],
};

export default meatTypes;
